### ISSUE TITLE
NOT working on arduino IDE 1.8.9

### ISSUE THREAD

**Issue by TasosR83** [sstaub/Ticker#4]
It works on Arduino 1.8.7 but NOT on 1.8.9

**Comment by sstaub** [comment]
Don't know what you mean, some error messages. It works for me on macOS.

**Comment by TasosR83** [comment]
on Windows and Linux I have the message:

` Ticker timerMeasureBL(MeasureBL, 2 * 1000);
status
                              ^
exit status 1
'MeasureBL' was not declared in this scope`

The program is the following:
```
#include "Ticker.h"    
Ticker timerMeasureBL(MeasureBL, 2 * 1000);
```

**Comment by sstaub** [comment]
Have you declared a callback function for MeasureBL?
You must also declare a prototype function for MeasureBL before setup.

**Comment by sstaub** [comment]
You must declare the function or prototype before you declare the class member, so after #include "Ticher.h" and before Ticker timerMeasureBL(MeasureBL, 2 * 1000);
